/*
 * This source file was generated by the Gradle 'init' task
 */
package com.gridnine;

import java.time.LocalDateTime;
import java.util.List;
import java.time.Duration;

import com.gridnine.testing.Flight;
import com.gridnine.testing.Segment;
import com.gridnine.testing.FlightBuilder;
import com.gridnine.testing.FlightFilterImpl;

public class App {
    public String getGreeting() {
        return "Hello Gridnine!";
    }

    public static void main(String[] args) {
        
        List<Flight> flights = FlightBuilder.createFlights();
        FlightFilterImpl filterService = new FlightFilterImpl(flights);

        System.out.println("--- Полный список перелетов ---");
        flights.forEach(System.out::println);

        // 1. Исключить вылет до текущего момента времени
        System.out.println("\n--- 1. Исключен вылет до текущего момента ---");
        List<Flight> filtered1 = filterService.filterBy(f -> f.stream()
                .filter(flight -> flight.getSegments().get(0).getDepartureDate().isAfter(LocalDateTime.now()))
                .collect(java.util.stream.Collectors.toList()));
        filtered1.forEach(System.out::println);

        // 2. Исключить сегменты с датой прилёта раньше даты вылета
        System.out.println("\n--- 2. Исключены сегменты с прилетом раньше вылета ---");
        List<Flight> filtered2 = filterService.filterBy(fList -> fList.stream()
                .filter(flight -> flight.getSegments().stream()
                        .allMatch(seg -> seg.getArrivalDate().isAfter(seg.getDepartureDate())))
                .collect(java.util.stream.Collectors.toList()));
        filtered2.forEach(System.out::println);

        // 3. Исключить перелеты, где общее время на земле > 2 часов
        System.out.println("\n--- 3. Исключено время на земле более 2 часов ---");
        List<Flight> filtered3 = filterService.filterBy(fList -> fList.stream()
                .filter(flight -> {
                    List<Segment> segs = flight.getSegments();
                    if (segs.size() <= 1) return true;
                    long groundTime = 0;
                    for (int i = 0; i < segs.size() - 1; i++) {
                        groundTime += Duration.between(segs.get(i).getArrivalDate(), 
                                                      segs.get(i + 1).getDepartureDate()).toHours();
                    }
                    return groundTime <= 2;
                })
                .collect(java.util.stream.Collectors.toList()));
        filtered3.forEach(System.out::println);
    }
}
